# Generated by Django 5.0.4 on 2024-05-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0002_contactenquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactEnquiry',
        ),
    ]
